# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/model/my_bighw/my_bighw.cache/wt [current_project]
set_property parent.project_path E:/model/my_bighw/my_bighw.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files E:/helopyyear/output.coe
add_files -quiet e:/model/my_bighw/my_bighw.srcs/sources_1/ip/vga_ram_1/vga_ram.dcp
set_property used_in_implementation false [get_files e:/model/my_bighw/my_bighw.srcs/sources_1/ip/vga_ram_1/vga_ram.dcp]
add_files -quiet e:/model/my_bighw/my_bighw.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files e:/model/my_bighw/my_bighw.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  E:/model/my_bighw/my_bighw.srcs/sources_1/new/keyboard.v
  E:/model/my_bighw/my_bighw.srcs/sources_1/new/vga.v
  E:/model/my_bighw/my_bighw.srcs/sources_1/new/key_translate.v
  E:/model/my_bighw/my_bighw.srcs/sources_1/new/convert_to_vga.v
  E:/model/my_bighw/my_bighw.srcs/sources_1/new/vga_top.v
  E:/model/my_bighw/my_bighw.srcs/sources_1/new/translate_line.v
  E:/model/my_bighw/my_bighw.srcs/sources_1/new/screen_top.v
  E:/model/my_bighw/my_bighw.srcs/sources_1/new/alu.v
  E:/model/my_bighw/my_bighw.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/model/my_bighw/my_bighw.srcs/constrs_1/new/vga_test_xdc.xdc
set_property used_in_implementation false [get_files E:/model/my_bighw/my_bighw.srcs/constrs_1/new/vga_test_xdc.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
